import turtle 

#Letra D
tortuga=turtle.Turtle()
tortuga.speed(100)
tortuga.pensize(12)
tortuga.penup()
tortuga.goto(-800,0)
tortuga.pendown()
tortuga.color("black")
tortuga.shape('turtle')
tortuga.forward(30)
tortuga.circle(75,180)
tortuga.forward(30)
tortuga.left(90)
tortuga.forward(150)

#Letra A
tortuga.penup()
tortuga.goto(-680,0)
tortuga.pendown()
tortuga.left(90)
tortuga.color("Red")
tortuga.left(70)
tortuga.forward(140)
tortuga.right(140)
tortuga.forward(140)
tortuga.right(180)
tortuga.penup()
tortuga.forward(60)
tortuga.left(70)
tortuga.pendown()
tortuga.forward(48)

#Letra N
tortuga.penup()
tortuga.goto(-560,0)
tortuga.right(90)
tortuga.pendown()
tortuga.color("blue")
tortuga.forward(140)
tortuga.right(150)
tortuga.forward(160)
tortuga.left(150)
tortuga.forward(140)

#Letra I
tortuga.penup()
tortuga.goto(-450,0)
tortuga.pendown()
tortuga.color("black")
tortuga.right(90)
tortuga.forward(60)
tortuga.penup()
tortuga.goto(-450,0)
tortuga.forward(30)
tortuga.pendown()
tortuga.left(90)
tortuga.forward(140)
tortuga.penup()
tortuga.goto(-450,140)
tortuga.pendown()
tortuga.right(90)
tortuga.forward(60)

#Letra E
tortuga.penup()
tortuga.goto(-360,0)
tortuga.left(90)
tortuga.pendown()
tortuga.color("Red")
tortuga.forward(140)
tortuga.right(90)
tortuga.forward(60)
tortuga.penup()
tortuga.goto(-360,0)
tortuga.pendown()
tortuga.forward(60)
tortuga.penup()
tortuga.goto(-360,0)
tortuga.left(90)
tortuga.forward(75)
tortuga.pendown()
tortuga.right(90)
tortuga.forward(50)

#Letra L
tortuga.penup()
tortuga.goto(-270,0)
tortuga.pendown()
tortuga.color("blue")
tortuga.forward(65)
tortuga.penup()
tortuga.goto(-270,0)
tortuga.pendown()
tortuga.left(90)
tortuga.forward(150)

#Letra R
tortuga.penup()
tortuga.goto(-50,0)
tortuga.right(90)
tortuga.pendown()
tortuga.color("black")
tortuga.left(90)
tortuga.forward(150)
tortuga.right(180)
tortuga.penup()
tortuga.forward(80)
tortuga.pendown()
tortuga.left(90)
tortuga.forward(30)
tortuga.circle(40,180)
tortuga.forward(30)
tortuga.left(90)
tortuga.penup()
tortuga.forward(80)
tortuga.left(90)
tortuga.forward(30)
tortuga.circle(40,15)
tortuga.right(75)
tortuga.pendown()
tortuga.forward(80)

#Letra O
tortuga.penup()
tortuga.goto(110,0)
tortuga.left(60)
tortuga.pendown()
tortuga.color("Red")
tortuga.circle(70,360)

#Letra S
tortuga.penup()
tortuga.goto(250,75)
tortuga.pendown()
tortuga.color("blue")
tortuga.circle(37.5,-250)
tortuga.penup()
tortuga.goto(250,77)
tortuga.pendown()
tortuga.left(65)
tortuga.circle(40,-240)

#Letra A
tortuga.penup()
tortuga.goto(315,0)
tortuga.left(65)
tortuga.pendown()
tortuga.color("black")
tortuga.left(70)
tortuga.forward(140)
tortuga.right(140)
tortuga.forward(140)
tortuga.right(180)
tortuga.penup()
tortuga.forward(60)
tortuga.left(70)
tortuga.pendown()
tortuga.forward(48)

#Letra S
tortuga.penup()
tortuga.goto(470,75)
tortuga.pendown()
tortuga.color("Red")
tortuga.circle(40,-250)
tortuga.penup()
tortuga.goto(470,77)
tortuga.pendown()
tortuga.left(65)
tortuga.circle(37.5,-240)